// Generated by CoffeeScript 1.6.3
(function() {
  var createBoard, createControls, createCopyright;

  window.createPlaymat = function(controlSelector, boardSelector, licenseSelector) {
    var boardElement, controlElement, licenseElement;
    boardElement = $('#' + boardSelector);
    controlElement = $('#' + controlSelector);
    licenseElement = $('#' + licenseSelector);
    if (boardElement && controlElement && licenseElement) {
      console.log("Found elements");
      createControls(controlElement);
      createBoard(boardElement);
      createCopyright(licenseElement);
      return $('head').append('<link rel="stylesheet" href="css/board.css" type="text/css" />');
    } else {
      return console.log("Elements not apparent");
    }
  };

  createBoard = function(inElement) {
    var aColumn, boardDiv, i, letter, _i, _results;
    boardDiv = $(document.createElement('div')).attr("id", "board").appendTo(inElement);
    _results = [];
    for (i = _i = 1; _i <= 8; i = ++_i) {
      letter = String.fromCharCode("A".charCodeAt(0) + i - 1);
      aColumn = $(document.createElement('div')).attr("class", "column").attr("id", "c" + i).appendTo(boardDiv);
      $(document.createElement('div')).attr("class", "feature").text("Feature " + letter).appendTo(aColumn);
      $(document.createElement('div')).attr("class", "detector").text("Detector " + letter).appendTo(aColumn);
      $(document.createElement('div')).attr("class", "effector e1").text("Effector " + letter + "1").appendTo(aColumn);
      $(document.createElement('div')).attr("class", "effector e2").text("Effector " + letter + "2").appendTo(aColumn);
      $(document.createElement('div')).attr("class", "alarm e1").text("Alarm " + letter + "1").appendTo(aColumn);
      _results.push($(document.createElement('div')).attr("class", "alarm e2").text("Alarm " + letter + "2").appendTo(aColumn));
    }
    return _results;
  };

  createControls = function(inElement) {
    var aTD, firstRow, i, secondRow, selector, theTable, _i, _j;
    theTable = $(document.createElement('table')).attr("style", "width:100%").appendTo(inElement);
    firstRow = $(document.createElement('tr')).appendTo(theTable);
    secondRow = $(document.createElement('tr')).appendTo(theTable);
    aTD = $(document.createElement('td')).attr("style", "width:20%").appendTo(firstRow);
    selector = $(document.createElement('select')).attr("style", "width:100%").attr("id", "comboBoard").appendTo(aTD);
    $(document.createElement('option')).attr("value", "").text("Select current board state").appendTo(selector);
    $(document.createElement('option')).attr("value", "ETI").text("ETI (Alarm matches Effector)").appendTo(selector);
    $(document.createElement('option')).attr("value", "MTI").text("MTI (Two active detectors match features)").appendTo(selector);
    $(document.createElement('option')).attr("value", "Virulence").text("Virulence (None of the above)").appendTo(selector);
    for (i = _i = 1; _i <= 3; i = ++_i) {
      aTD = $(document.createElement('td')).appendTo(firstRow);
      $(document.createElement('div')).attr("id", "Quiz" + i).html("Training " + i + "<br>Answers: 0 Correct: 0<br>ETI:0 MTI:0 Virulence:0").appendTo(aTD);
    }
    aTD = $(document.createElement('td')).appendTo(secondRow);
    for (i = _j = 0; _j <= 4; i = ++_j) {
      $(document.createElement('button')).attr("id", "cheatyFace" + (i + 1)).attr("type", "button").text("10^" + i).appendTo(aTD);
    }
    aTD = $(document.createElement('td')).attr("colspan", 3).appendTo(secondRow);
    return $(document.createElement('div')).attr("id", "ClearBoardButton").text("Clear Board").appendTo(aTD);
  };

  createCopyright = function(inElement) {
    var agplLogo, agplURL;
    agplLogo = $(document.createElement('img')).attr("src", "agplv3-88x31.png");
    agplURL = $(document.createElement('href')).attr("href", "http://www.gnu.org/licenses/agpl.html").append(agplLogo);
    inElement.html('<a href="https://github.com/b-adams/RQCards">Source</a> for this project available under the <a href="http://www.gnu.org/licenses/agpl.html">AGPLv3</a>');
    return inElement.prepend(agplURL);
  };

}).call(this);
