// Generated by CoffeeScript 1.6.3
(function() {
  describe('Model Playmat', function() {
    var mat;
    mat = null;
    beforeEach(function() {
      return mat = new PlayMat();
    });
    afterEach(function() {
      return mat = null;
    });
    it('starts with an inactive feature', function() {
      var result;
      result = mat.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeFalsy();
    });
    it('allows features to be toggled on', function() {
      var result;
      mat.toggleCell(TYPE_FEATURE, 1);
      result = mat.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeTruthy();
    });
    return it('allows features to be toggled back off', function() {
      var result;
      mat.toggleCell(TYPE_FEATURE, 1);
      mat.toggleCell(TYPE_FEATURE, 1);
      result = mat.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeFalsy();
    });
  });

}).call(this);
