// Generated by CoffeeScript 1.6.3
(function() {
  describe('Model Playmat', function() {
    var sut;
    sut = null;
    beforeEach(function() {
      return sut = new PlayMat();
    });
    afterEach(function() {
      return sut = null;
    });
    it('starts with an inactive feature', function() {
      var result;
      result = sut.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeFalsy();
    });
    it('calls setCell when toggling a cell', function() {
      spyOn(sut, "setCell");
      sut.toggleCell(TYPE_FEATURE, 1);
      return expect(sut.setCell).toHaveBeenCalled;
    });
    it('allows features to be toggled on', function() {
      var result;
      sut.toggleCell(TYPE_FEATURE, 1);
      result = sut.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeTruthy();
    });
    return it('allows features to be toggled back off', function() {
      var result;
      sut.toggleCell(TYPE_FEATURE, 1);
      sut.toggleCell(TYPE_FEATURE, 1);
      result = sut.isCellActive(TYPE_FEATURE, 1);
      return expect(result).toBeFalsy();
    });
  });

}).call(this);
