// Generated by CoffeeScript 1.6.3
(function() {
  describe('Controller', function() {
    var sut;
    sut = null;
    beforeEach(function() {
      return sut = new PlayMatController();
    });
    afterEach(function() {
      return sut = null;
    });
    return describe('Toggling', function() {
      it('has a model', function() {
        var model;
        model = sut.model;
        return expect(model).toBeDefined();
      });
      return it('calls setCell when toggling', function() {
        spyOn(sut, "setCell");
        sut.toggleCell(cellType, 2);
        return expect(sut.setCell).toHaveBeenCalled;
      });
    });
  });

}).call(this);
